FROM python:3.9.1 as build
#FROM ubuntu:20.04 as build

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

RUN apt-get update  && apt-get install -y --no-install-recommends build-essential swig libsundials-dev libboost-all-dev && apt-get purge -y --auto-remove && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN apt-get update -y &&  apt-get install python3-venv -y
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"


RUN apt-get update -y && apt install ca-certificates -y && apt-get install curl -y \
    && curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
    && python3 get-pip.py \
    && rm get-pip.py

RUN pip install -r requirements.txt


#FROM ubuntu:20.04
FROM python:3.9.1

# per le GUI...
RUN apt-get update -y && apt-get install libboost-all-dev  -y && apt-get install python3-tk -y


ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY --from=build /opt/venv /opt/venv

RUN mkdir /home/dt-rse-mosaik
WORKDIR /home/dt-rse-mosaik
CMD tail -f /dev/null
