#FROM python:3.9.1
FROM ubuntu:20.04

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

RUN apt-get update  && apt-get install -y --no-install-recommends build-essential swig libsundials-dev libboost-all-dev && apt-get purge -y --auto-remove && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

# RUN pip install -r requirements.txt

RUN mkdir /home/dt-rse-mosaik
WORKDIR /home/dt-rse-mosaik
CMD tail -f /dev/null
