FROM ubuntu:20.04
# FROM aguagliardi/test_matlab:2.0_r2017a_full
# RUN apt-get update && apt-get upgrade -y && apt-get autoremove && apt-get autoclean 
# RUN apt-get update -y && apt-get autoremove && apt-get autoclean  

#RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && apt-get install -y --no-install-recommends build-essential swig libsundials-dev libboost-all-dev && apt-get purge -y --auto-remove && rm -rf /var/lib/apt/lists/*

#RUN apt-get install python3 -y && \
#    apt-get install python3-pip -y && \
# add deadsnakes ppa
# RUN apt install --reinstall software-properties-common

RUN apt-get update -y && apt-get install -y libsystemd0 networkd-dispatcher libsystemd0 systemd systemd-sysv policykit-1 libpam-systemd packagekit && apt-get -y install software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update -y

# install python
RUN apt-get install python3.10 -y \
    && apt-get install python3.9-distutils -y

# remove old, default python version
## RUN apt remove python3.5-minimal -y

# Create a python3 symlink pointing to latest python version
RUN ln -sf /usr/bin/python3.10 /usr/bin/python3

RUN apt-get install curl -y  && \ 
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
    && python3 get-pip.py \
    && rm get-pip.py
RUN apt-get update -y && apt-get install python-dev -y && apt-get install apt-utils -y
COPY requirements.txt ./requirements.txt
COPY requirements_senzaversione.txt ./requirements_senzaversione.txt
# COPY requirements.txt .
RUN pip install -r requirements_senzaversione.txt

RUN mkdir /home/dt-rse-mosaik
WORKDIR /home/dt-rse-mosaik

#COPY ./MAPSfun 
#CMD ["python3","startMatlabTEO.py"]
CMD ["/bin/bash"]
