#!/bin/bash
set -x
DTSERVLOCALE=.
$DTSERVLOCALE/DTminiostop; sleep 1;  $DTSERVLOCALE/DTRedisStop; $DTSERVLOCALE/DTinfluxdbstop; $DTSERVLOCALE/DTmqttstop
./DTstop
#docker-compose -f docker-compose_conRedis.yaml down --remove-orphans 
