# ################## #
# Comunication Options #
# ################## #

redis:
    redis_host: 'REDIS_HOST'
    redis_host_default: 'localhost'
    redis_port: 'REDIS_PORT'
    redis_port_default: 6380
    redis_password: 'mypassw'
    DT:mode: 'SIM'
    DT:mode_set: '0'

mqtt:
    DTSDA:
        BATT1:
           temperatura: 35
           tensione: 5.1
           corrente: 10.2
        SIM: True
        LEARN: False
        RUNSIM: True
        STOPSIM: False


    




