version: '2.0'
  DTSDAServ:
    build:
      context: .
      dockerfile: Dockerfile_python38
    image: aguagliardi/dtsda:2.0
    #image: dtsda38
    container_name: DTSDA
    depends_on:
      - DTredis
    networks:
      - DT-net
    environment:
      DISPLAY: $DISPLAY
      REDIS_HOST: DTredis
      REDIS_PORT: 6380
      REDIS_PASSWORD: mypassw
    volumes:
      - "../..:/home/dt-rse-mosaik"
      - "/tmp/.X11-unix:/tmp/.X11-unix"

networks:
  DT-net:
#    driver: bridge  
    external: true

