version: '2.0'
services:
  DTSDAServ:
    build:
      context: .
      dockerfile: Dockerfile_python38
    #image: dtsda38
    image: aguagliardi/dtsda:2.0
    container_name: DTSDA
    environment:
      - DISPLAY
    volumes:
      - "../..:/home/dt-rse-mosaik"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
