#!/bin/bash
set -x
DTSERV=../../../ServicesEtc
cd $DTSERV/redis
sudo docker-compose  -f docker-compose2.yml up  -d
# docker-compose  -f docker-compose_SOLORedis.yaml up  --remove-orphans -d
docker ps
