#!/bin/bash
set -x
DTSERV=.
$DTSERV/DTminiostart; sleep 1;  $DTSERV/DTRedisStart; $DTSERV/DTinfluxdbstart; $DTSERV/DTmqttstart
./DTstart
./DTRun
#docker-compose -f docker-compose_conRedis.yaml up --remove-orphans -d
