#!/bin/bash
set -x
DTSERV=.
$DTSERV/DTminiostop; sleep 1;  $DTSERV/DTRedisStop; $DTSERV/DTinfluxdbstop; $DTSERV/DTmqttstop
./DTstop
#docker-compose -f docker-compose_conRedis.yaml down --remove-orphans 
