#!/bin/bash
set -x
SERV=.
$SERV/DTminiostart; sleep 1;  $SERV/DTRedisStart; $SERV/DTinfluxdbstart; $SERV/DTmqttstart
./DTstart
./DTRun
#docker-compose -f docker-compose_conRedis.yaml up --remove-orphans -d
