# ############################
# Communication MESP Options #
# VERSIONE SERVIZI LOCALI    #
# ############################
versione: "SERVIZI_LOCALI"
serv_hmi: "https://mesp-sda.rse-web.it/frontend/sda-dt.html"
serv_ip:  &MIP "localhost"   # redis host, mqqt brocker, mesp hmi
serv_ip9000:  &MIP9090 "localhost:9090"  # endpoint minio
serv_ip9090:  &MIP9091 "localgost:9091"  # console minio
serv_ip8086:  &MIP8086 "http://localhost:8086"  # influxdb server

redis:
  redis_host: REDIS_HOST
  redis_host_default: localhost
  redis_port: REDIS_PORT
  redis_port_default: 6380
  redis_password: mypassw
  
  htags:
    - DTSDA:batt1
  batt1:
    id: batt1
    DTmode:
      field: mode
      value: S_SIM
    DTmode_set:
      field: mode_set
      value: S_SIM
    DTSDA_State:
      field: state
      value: S_IDLE
    tsim:
      field: tsim
      value: 0
    output_voltage:
      field: output_voltage
      value: 0
    load_current:
      field: load_current
      value: 0

mqtt:
        #  SERVER: "0.0.0.0"
  SERVER: *MIP
  PORT: "1883"
  USER: "userDT"
  PASSWORD: "userDT"
  WEBSOCKETPORT: "9001"
  DTSDA:
    MISURE:
      BATT1:
        temperatura: "DTSDA/BATT1/T"
        tensione: "DTSDA/BATT1/V"
        corrente: "DTSDA/BATT1/I"
    # associazione Callback --> TagComando_mqtt
    CALLBACK:                             # Comandi GET ricevuti dal HMI e callbacks associate
      MainCall:  "DTSDA"
      SetModoSIM:   "DTSDA/SET_SIM"       # payload: {"command":"SET_SIM"}
      SetModoLEARN: "DTSDA/SET_LEARN"     # payload: {"command":"SET_LEARN"}
      InitSIM:      "DTSDA/INIT_SIM"      # payload: {"command":"INIT_SIM"}
      RunSIM:       "DTSDA/RUN_SIM"       # payload: {"command": "RUN_SIM"}
      StopSIM:      "DTSDA/STOP_SIM"      # payload: {"command": "STOP_SIM"}
      EndProg:      "DTSDA/END"            # payload: {"command": "END"}
      PlotGraf:     "DTSDA/PLOTGRAF"       # payload: {"command": "PLOTGRAF"}      
      CurrConfReq:  "DTSDA/CURRCONF_REQ"    # payload: {"command": "CURRCONF_REQ","id":"uidx"}        Richiesta della configurazione corrente, es:  "DTSDA/CURRCONF_REQ"
      LoadConf:     "DTSDA/LOADCONF"        # payload: {"command": "LOADCONF", "id": "conf1"}         Richiesta configurazione da caricare, es:  "DTSDA/LOADCONF  conf1"
      SaveConf:     "DTSDA/SAVECONF"        # payload: {"command": "SAVECONF", "id": "conf1", "descr":"descrizione di descr"}            Richiesta configurazione da salvare, es:  "DTSDA/SAVECONF  conf1"
      ListaConfReq: "DTSDA/LISTCONF_REQ"    # payload: {"command": "LISTCONF_REQ","id":"uidx"}         Richiesta della lista delle configurazioni salvate in minio. Ad es: "DTSDA/LISTCONF_REQ"
      DelConf:      "DTSDA/DELCONF"         #  payload: {"command": "DELCONF", "id": "conf1"}          Rimozione di una configurazione salvata in minio. es: "DTSDA/DELCONF  conf1"
      StatusReq:    "DTSDA/STATUS_REQ"      # payload: {"command": "STATUS_REQ"} Richiesta stato redis hash DTSDA:batt1
      HealthReq:    "DTSDA/HEALTHCHECK_REQ"  # Richiesta di haelthcheck

    POST:
      listaconf: "DTSDA/LISTCONF"         # Lista delle configurazioni (per HMI)  salvate in minio e pubblicata da DTSDA nel mqtt brocker (come testo).      # Esempio comando di pubblicazione: "DTSDA/LIST_CONF  listaconf"
      currconf: "DTSDA/CURRCONF"          # Configurazione corrente, es:  "DTSDA/CURRCONF  currconf"
      status: "DTSDA/STATUS"              # esempio payload: {"state": "S_IDLE", "mode": "S_SIM", "mode_set": "S_SIM", "tsim": "6", "output_voltage": "4.254", "load_current": "32.000"}
      health: "DTSDA/HEALTHCHECK"         # 
      
    COMMAND:                             # Comandi GET ricevuti dal HMI e callbacks associate
      MainCall:  "DTSDA"                # topic per tutti i comandi 
      SetModoSIM:   "SET_SIM"           # payload: {"command":"SET_SIM"}
      SetModoLEARN: "SET_LEARN"         # payload: {"command":"SET_LEARN"}
      InitSIM:      "INIT_SIM"          # payload: {"command":"INIT_SIM"}
      RunSIM:       "RUN_SIM"           # payload: {"command": "RUN_SIM"}
      StopSIM:      "STOP_SIM"          # payload: {"command": "STOP_SIM"}
      EndProg:      "END"          # payload: {"command": "END"}
      PlotGraf:     "PLOTGRAF"          # payload: {"command": "PLOTGRAF"}
      CurrConfReq:  "CURRCONF_REQ"    # payload: {"command": "CURRCONF_REQ","id":"uidx"}       Richiesta della configurazione corrente, es:  "DTSDA/CURRCONF_REQ"
      LoadConf:     "LOADCONF"        # payload: {"command": "LOADCONF", "id": "conf1"}        Richiesta configurazione da caricare, es:  "DTSDA/LOADCONF  conf1"
      SaveConf: "SAVECONF"            # payload: {"command": "SAVECONF", "id": "conf1", "descr":"descrizione di descr"}            Richiesta configurazione da salvare, es:  "DTSDA/SAVECONF  conf1"
      ListaConfReq: "LISTCONF_REQ"    # payload: {"command": "LISTCONF_REQ","id":"uidx"}        Richiesta dSella lista delle configurazioni salvate in minio. Ad es: "DTSDA/LISTCONF_REQ"
      DelConf: "DELCONF"              #  payload: {"command": "DELCONF", "id": "conf1"}         Rimozione di una configurazione salvata in minio. es: "DTSDA/DELCONF  conf1"
    POST2:
      listaconf: "LISTCONF"          # esempio payload: "{"command": "LISTCONF", "id": "UID", "description":""{"Confxx": {"name": "Confxx", "description": "Descrizione Confxx", "date": "2024-05-30 15:08:57.229179"}, { "Conf22":{ ...}}}"."} Lista delle configurazioni (per HMI)  salvate in minio e pubblicata da DTSDA nel mqtt brocker (come testo).     # Esempio comando di pubblicazione: "DTSDA/LIST_CONF  listaconf"
      currconf: "CURRCONF"           # esempio payload: "{"command": "CURRCONF","id": "UID","description":{"name": "Confxx", "description": "Descrizione Confxx", "date": "2024-05-30 15:08:57.229179"}" Configurazione corrente, es:  "DTSDA/CURRCONF  currconf"

minio:
  ENDPOINT: *MIP9090
#  ACCESS_KEY: "4K10mbUN3FxVsDxtDYSh"
#  SECRET_KEY: "sI0zu0b4DlR2Vs0JyO6KhJZzws1w5eL1GzthLtPD"
  ACCESS_KEY: "oouICbtT7IsE0HQpmVWg"
  SECRET_KEY: "8DvNcONsS0TwoCbiuLHdZDxoWgS0IxeQKOqkR1Pv"
  SECURE: False
  CONSOLE: *MIP9091
  USER: "admin"           # utilizzato solo in console
  PASSWORD: "password"   # utilizzato solo in console
# per il file di index  
  INDEXNAME: "DTindex.jsonld"
  INDEXBUCKET: "dtsda"
  INDEXCONTEXT: "http://schema.org/"
  INDEX_CTX: "@context"
  INDEX_UID: "@id"
  INDEX_NAME: "name"
  INDEX_DESCRIPTION: "description"
  INDEX_DATA: "data"


influxdb:
  URL: *MIP8086
  ORG: "RSE"
  BUCKET: "nuovobuck"    # il bucket deve essere già esistente
  TOKEN: "aHMudy-R1gicVNWRDzVTWmw4_HPFVCdwzcUTIErKl_i2uVRpCrCpmTOtcOAg0n-qNdnuetSQfTKGHAmgsMeL4A=="
  MEASUREMENT: "experiment_0001"
  USER: "influxuser"     # utilizzato solo in console
  PASSWORD: "DTpass!!"   # utilizzato solo in console

rdf:
  NAMESPACE: "http://tgm-sda.rse-web.it/"
  INDEXPATH: "index.json"

