# ############################
# Communication MESP Options #
# ############################

redis:
  redis_host: "REDIS_HOST"
  redis_host_default: "localhost"
  redis_port: "REDIS_PORT"
  redis_port_default: 6380
  redis_password: "mypassw"
  DTSDA:
    DTmode:
      - "DTSDA:mode"
      - "SIM"
    DTmode_set:
      - "DTSDA:mode_set"
      - "0"
    DTSDA_State:
      - "DTSDA:STATE"
      - "IDLE"

mqtt:
        #  SERVER: "0.0.0.0"
  SERVER: "localhost"
  PORT: "1883"
  USER: "userDT"
  PASSWORD: "userDT"
  DTSDA:
    MISURE:
      BATT1:
        temperatura: "DTSDA/BATT1/T"
        tensione: "DTSDA/BATT1/V"
        corrente: "DTSDA/BATT1/I"
    # associazione Callback --> TagComando_mqtt
    CALLBACK:                             # Comandi GET ricevuti dal HMI e callbacks associate
      SetModoSIM: "DTSDA/SET_SIM"
      SetModoLEARN: "DTSDA/SET_LEARN"
      LoadSIM: "DTSDA/LOAD_SIM"
      RunSIM: "DTSDA/RUN_SIM"
      StopSIM: "DTSDA/STOP_SIM"
      EndProg: "DTSDA/END"
      PlotGraf: "DTSDA/PLOTGRAF"           
      LoadConf: "DTSDA/LOADCONF"           # Richiesta configurazione da caricare, es:  "DTSDA/LOADCONF  conf1"
      SaveConf: "DTSDA/SAVECONF"           # Richiesta configurazione da salvare, es:  "DTSDA/SAVECONF  conf1"
      LoadConfList: "DTSDA/LIST_CONF_REQ"  # Richiesta della lista delle configurazioni salvate in minio. Ad es: "DTSDA/LIST_CONF_REQ"
      DelConf: "DTSDA/DELCONF"             # Rimozione di una configurazione salvata in minio. es: "DTSDA/DELCONF  conf1"
    POST:
      listaconf: "DTSDA/LIST_CONF"         # Lista delle configurazioni salvate in minio e pubblicata da DTSDA nel mqtt brocker (come testo) per il HMI. 
                                           # Esempio comando di pubblicazione: "DTSDA/LIST_CONF  listaconf". 

minio:
  ENDPOINT: "localhost:9090"
#  ACCESS_KEY: "4K10mbUN3FxVsDxtDYSh"
#  SECRET_KEY: "sI0zu0b4DlR2Vs0JyO6KhJZzws1w5eL1GzthLtPD"
  ACCESS_KEY: "oouICbtT7IsE0HQpmVWg"
  SECRET_KEY: "8DvNcONsS0TwoCbiuLHdZDxoWgS0IxeQKOqkR1Pv"
  SECURE: False
  CONSOLE: "localhost:9091"
  USER: "admin"           # utilizzato solo in console
  PASSWORD: "password"   # utilizzato solo in console
# per il file di index  
  INDEXNAME: "DTindex.jsonld"
  INDEXBUCKET: "dtsda"
  INDEXCONTEXT: "http://schema.org/"
  INDEX_CTX: "@context"
  INDEX_UID: "@id"
  INDEX_NAME: "name"
  INDEX_DESCRIPTION: "description"
  INDEX_DATA: "data"


influxdb:
  URL: "http://localhost:8086"
  ORG: "RSE"
  BUCKET: "nuovobuck"    # il bucket deve essere già esistente
  TOKEN: "aHMudy-R1gicVNWRDzVTWmw4_HPFVCdwzcUTIErKl_i2uVRpCrCpmTOtcOAg0n-qNdnuetSQfTKGHAmgsMeL4A=="
  MEASUREMENT: "experiment_0001"
  USER: "influxuser"     # utilizzato solo in console
  PASSWORD: "DTpass!!"   # utilizzato solo in console

RDF_v2:
  - ['dtsdabuck', 'hold', 'index', '', '']
  - ['dtsdabuck', 'hold', 'conf1', 'timestamp1', 'Questa è la descrizione di conf1']
  - ['dtsdabuck', 'hold', 'conf2', 'timestamp2', 'Questa è la descrizione di conf2']
